name: manage-azure-policy-1f22428a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/TEMPLATE_-_Audit_and_deploy_Resource_Locks_on_Resource_Groups_based_on_Tags_01264850-34c7-4c28-b724-9abdee5354f2/**'
#      - 'policies/TEMPLATE_-_Require_multiple_tags_on_resources_47edcb7e-bee4-4c9a-8f2e-77617fc36f5c/**'
#      - .github/workflows/manage-azure-policy-1f22428a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1f22428a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/TEMPLATE_-_Audit_and_deploy_Resource_Locks_on_Resource_Groups_based_on_Tags_01264850-34c7-4c28-b724-9abdee5354f2/**
          policies/TEMPLATE_-_Require_multiple_tags_on_resources_47edcb7e-bee4-4c9a-8f2e-77617fc36f5c/**
